language: csharp
dist: trusty
mono: none
dotnet: 2.1.0
os:
- linux
- osx
osx_image: xcode9
matrix:
  allow_failures:
    - os: osx
install:
- dotnet restore
script:
- for testProject in *.Test; do dotnet test "$testProject"; done
