version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
install:
before_build:
  - choco install codecov
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  - ps: Get-ChildItem -Filter "*.Test" -Attributes Directory | Foreach-Object { dotnet test $_.FullName /p:CollectCoverage=true /p:CoverletOutputFormat=opencover; codecov -f "$_/coverage.opencover.xml" -t "6fec9a34-1f39-4274-9570-10404d134c36" }
on_finish :
  # any cleanup in here
deploy: off